run badfish as a container
redhat-performance/jetpack pull request #177
Opened 2020-04-15 12:35 UTC by asyedham

fix #176

2020-04-15 13:06 UTC, smalleni commented on setup_undercloud.yml
> +          shell: docker pull quads/badfish
Why not use podman module. Please run using podman.

2020-04-15 13:10 UTC, smalleni commented on setup_undercloud.yml
> +          shell: docker pull quads/badfish
podman_image

2020-04-15 13:10 UTC, smalleni commented on group_vars/all.yml
> +dns_ip: 10.1.32.3
Not needed

2020-04-15 13:10 UTC, smalleni commented on group_vars/all.yml
> +dns_ip: 10.1.32.3
Also you can add badfish_image as a variable and use it when you pull the podman image.

2020-04-15 13:12 UTC, smalleni commented on setup_undercloud.yml
> +              docker run --rm --dns {{ dns_ip }} quads/badfish -H mgmt-{{ undercloud_hostname }} -u quads -p {{ chassis_password }} --pxe
Use podman and you don't need DNS
For example,
podman run -it --rm {{ badfish_pod_image }} -u  quads-p {{ chassis_assword }} -i config/idrac_interfaces.yml

2020-04-15 13:12 UTC, smalleni requested changes
Please make suggested changes.

2020-05-11 07:17 UTC, asyedham commented
Closing this PR. As we need to manually install podman packages. (i.e  it may be vary depending on OS)

2020-05-12 14:42 UTC, smalleni commented
For all Red Hat based distros it should be yum/dnf . However we can use ansible package module. I don't think we need to deal with repos (it's beyond the scope)

2020-05-13 04:29 UTC, asyedham commented
For Red Hat based distros we need to enable extra repo  to install podman e.g for RHEL 7 ``rhel-7-server-extras-beta-rpms``

2020-06-22 05:22 UTC, closed without merging