automate vm_image_url and virtual_uc_ctlpane_interface
redhat-performance/jetpack pull request #185
Opened 2020-05-03 07:22 UTC by Shrutikabansal

update the vm_image_url based on the osp version and virtual_uc_ctlpane_interface based on the machine type

2020-05-03 07:27 UTC, masco commented
Can one of the admins verify this patch?

2020-05-03 17:33 UTC, asyedham requested changes

2020-05-03 17:33 UTC, asyedham commented on group_vars/all.yml
> +virtual_uc: true
set to false

2020-05-03 17:33 UTC, asyedham commented on main.yml
> +- import_playbook: prepare_nic_configs_virtual.yml
not needed. use the existing one as it seems just duplication of existing code

2020-05-03 17:33 UTC, asyedham commented on tasks/load_instackenv.yml
> +- name: skip first node of instack env file
not needed. It was only for you to understand  the code :)

2020-05-03 17:33 UTC, asyedham commented on tasks/load_instackenv.yml
> +
not needed

2020-05-05 15:23 UTC, asyedham commented
run tests

2020-05-06 17:55 UTC, closed without merging