automate_virtual_uc_ctlpane_interface
redhat-performance/jetpack pull request #225
Opened 2020-07-07 14:56 UTC by Shrutikabansal

automate  virtual_uc_ctlpane_interface for virtual_undercloud

2020-07-07 14:56 UTC, masco commented
Can one of the admins verify this patch?

2020-07-07 15:22 UTC, Shrutikabansal commented
@asyedham would you review it.

2020-07-08 07:12 UTC, asyedham requested changes

2020-07-08 07:12 UTC, asyedham commented on group_vars/all.yml
> +#virtual_uc_ctlplane_interface: em1
remove this

2020-07-08 09:49 UTC, Shrutikabansal commented on group_vars/all.yml
> +#virtual_uc_ctlplane_interface: em1
@asyedham chanages done

2020-08-17 10:47 UTC, closed without merging