Add root_hints for 740xd G-CL
redhat-performance/jetpack pull request #412
Opened 2021-10-27 12:39 UTC by asyedham

2021-10-27 13:13 UTC, masco commented
If i have mix of systems how this will behave?

2021-10-27 16:15 UTC, asyedham commented
@masco I have added a check to ensure root_hints is only enabled on 740xd's on rack e26 and skips setting root_hints for the rest of 740xd's

2021-10-28 06:31 UTC, sanjaychari commented
This PR gives the error
```
fatal: [undercloud]: FAILED! => {
    "msg": "The conditional check 'lab_name == 'alias' and machine_type == '740xd' and instackenv_content.nodes[0]['pm_addr'].split('.')[0].split('-')[1] == 'e26'' failed. The error was: error while evaluating conditional (lab_name == 'alias' and machine_type == '740xd' and instackenv_content.nodes[0]['pm_addr'].split('.')[0].split('-')[1] == 'e26'): 'machine_type' is undefined\n\nThe error appears to be in '/var/lib/jenkins/workspace/OSP-API-tester/jetpack/introspect.yml': line 47, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: enable root_hints(740xd G-CL)\n        ^ here\n"
}
```
I think this is because we are trying to use the variable `machine_type` which is set on localhost, but not on undercloud.

2021-10-28 08:30 UTC, sanjaychari commented
Now getting the error
```
fatal: [undercloud]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'node_uuids' is undefined\n\nThe error appears to be in '/var/lib/jenkins/workspace/OSP-API-tester/jetpack/tasks/set_root_hints.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: using introspection data to set root device\n  ^ here\n"
}
```

2021-10-29 12:36 UTC, masco commented on introspect.yml
> +        when: lab_name == 'alias' and hostvars['localhost']['machine_type'] == '740xd' and hostvars['localhost']['instackenv_content'].nodes[0]['pm_addr'].split('.')[0].split('-')[1] == 'e26'
this playbook will be invoked only if the first node of instack_env in e26 rack right? or am I missing something?

2021-11-17 09:47 UTC, asyedham commented on introspect.yml
> +        when: lab_name == 'alias' and hostvars['localhost']['machine_type'] == '740xd' and hostvars['localhost']['instackenv_content'].nodes[0]['pm_addr'].split('.')[0].split('-')[1] == 'e26'
@masco Done

2021-11-17 09:53 UTC, sanjaychari commented
@asyedham Chris had mentioned that racks e26-e29 contain G-CL servers. So maybe this PR should check for the range e26-e29 instead of only e26?

2021-11-17 09:56 UTC, asyedham commented
> @asyedham Chris had mentioned that racks e26-e29 contain G-CL servers. So maybe this PR should check for the range e26-e29 instead of only e26?

@sanjaychari Let's not add the logic now without testing it on machines from e29 rack,

2021-11-17 09:57 UTC, sanjaychari commented
> > @asyedham Chris had mentioned that racks e26-e29 contain G-CL servers. So maybe this PR should check for the range e26-e29 instead of only e26?
> 
> @sanjaychari Let's not add the logic now without testing it on machines from e29 rack,

@asyedham Ack

2021-11-18 04:38 UTC, sanjaychari commented
Facing this error with the latest changes.
```
TASK [set fact for e26 rack machines in instackenv] ****************************
task path: /var/lib/jenkins/workspace/OSP-API-tester@2/jetpack/introspect.yml:47
Wednesday 17 November 2021  14:03:48 +0000 (0:00:00.056)       1:44:35.506 **** 
fatal: [undercloud]: FAILED! => {
    "msg": "'instackenv_content' is undefined"
}
```

2021-11-18 04:46 UTC, sanjaychari commented
> Facing this error with the latest changes.
> 
> ```
> TASK [set fact for e26 rack machines in instackenv] ****************************
> task path: /var/lib/jenkins/workspace/OSP-API-tester@2/jetpack/introspect.yml:47
> Wednesday 17 November 2021  14:03:48 +0000 (0:00:00.056)       1:44:35.506 **** 
> fatal: [undercloud]: FAILED! => {
>     "msg": "'instackenv_content' is undefined"
> }
> ```

I think we might have to use `hostvars['localhost']['instackenv_content']` instead of `instackenv_content`?

2021-11-18 06:09 UTC, sanjaychari commented
`ansible-playbook -vvv main.yml` deployed OSP 16.1 with this patch successfully on 740xd G-CL systems. I will trigger a CI build to try out deployment with tags as well.

2021-11-18 09:06 UTC, masco requested changes

2021-11-18 09:06 UTC, masco commented on introspect.yml
> +          rack: "{{ rack_info }}"
if the cloud doesn't have any machine from e26 rack, this will become undefined and cause an error at line number 58.

2021-11-18 09:52 UTC, asyedham commented on introspect.yml
> +          rack: "{{ rack_info }}"
@masco fixed it

2021-11-18 10:16 UTC, masco approved these changes
LGTM

2021-11-18 10:16 UTC, merged