Add support for badfish parallel execution
redhat-performance/jetpack pull request #459
Opened 2022-07-07 08:14 UTC by rajeshP524

when we have list of baremetal systems to be managed by badfish,
it can take list of all baremetal nodes at once and operate on each simultaneously

2022-07-08 08:34 UTC, asyedham requested changes

2022-07-08 08:34 UTC, asyedham commented on common.yml
> +            path: "~/jetpack/badfish/dell-hosts"
use "{{ playbook_dir }}/badfish/dell-hosts" as this may cause failures in ci

2022-07-08 08:34 UTC, asyedham commented on common.yml
> +        shell: echo "mgmt-{{ item[1].stdout }}" >> ~/jetpack/badfish/dell-hosts
same here

2022-07-08 08:34 UTC, asyedham commented on common.yml
> +        shell: podman build --tag badfish:latest -f ~/jetpack/badfish/Dockerfile
same here

2022-07-08 10:04 UTC, sanjaychari requested changes

2022-07-08 10:04 UTC, sanjaychari commented on badfish/Dockerfile
> +COPY dell-hosts /
The pull rate limit issue that you are facing can be avoided by not removing and pulling the image again each time. Instead of adding `COPY dell-hosts` here and having a separate Dockerfile for badfish, you can just replace lines 80-88 in common.yml with a task that runs `podman pull quay.io/quads/badfish` if the image is not the latest version.
Then, every time when you call `podman run`, you can just use `-v dell-hosts:/dell-hosts`.
Using bind mounting on the container is much more efficient than using COPY in the Dockerfile and removing the image each time.

2022-07-08 10:12 UTC, rajeshP524 commented on badfish/Dockerfile
> +COPY dell-hosts /
ack

2022-07-08 10:12 UTC, rajeshP524 commented on common.yml
> +            path: "~/jetpack/badfish/dell-hosts"
ack

2022-07-20 12:56 UTC, asyedham requested changes

2022-07-20 12:56 UTC, asyedham commented on bootstrap.yml
> +      - name: set SELinux to Permissive
use ansible in-built module to put SELinux in permissive mode

2022-07-21 03:19 UTC, rajeshP524 commented on bootstrap.yml
> +      - name: set SELinux to Permissive
as ansible in-built module requires a reboot to get changes reflected, I have removed this task and added it as a requirement in readme file

2022-07-22 07:45 UTC, asyedham approved these changes
LGTM!

2022-07-22 07:45 UTC, merged