Minimise use of ovs bridges in OSP17
redhat-performance/jetpack pull request #501
Opened 2022-11-09 05:28 UTC by sanjaychari

This PR moves internal-api, storage and storage-mgmt networks away from ovs bridges and onto the linux interface directly, to reduce load on ovs. manila is not supported in Jetpack yet for OSP 17, but manila requires an ovn bridge mapping on the br-isolated bridge, and that is why the ovs bridge br-isolated is created, similar to how it was before, when manila is enabled. This commit is for OSP 17. The changes for other OSP releases will be addressed in separate PRs. This PR has been tested on a 16 node environment with ceph enabled with composable roles for heterogeneous hardware.

Partially addresses #433

2022-11-09 06:38 UTC, pradiptapks requested changes
@sanjaychari It makes sense to remove the isolated network from the ovs-bridge. You can also remove `ctlplane` network mapping from ovs as well.

2022-11-09 06:51 UTC, sanjaychari commented
@pradiptapks ctlplane network is already not on ovs bridge in OSP 17 when external network is not on the same interface as ctlplane network. 
https://github.com/redhat-performance/jetpack/blob/master/templates/controller.j2.j2#L29-L44

When external network and ctlplane network have to be on same interface due to lack of sufficient interfaces, then an ovs bridge is created to host both of them because external network needs ovs bridge.
https://github.com/redhat-performance/jetpack/blob/master/templates/controller.j2.j2#L67-L86

So I do not think any change is required for ctlplane network in OSP 17 templates. In OSP 16 templates, ctlplane network is using ovs-bridge br-ctlplane like you mentioned. So that will have to be changed in OSP 16. I will address the OSP 16 changes in a separate PR.

2022-11-09 07:16 UTC, pradiptapks commented
@sanjaychari Thank you for the details. You can create another PR for OSP16 network changes similar to OSP17 network configuration.

These chages can help for nfv best practices as well.

2022-11-09 07:23 UTC, pradiptapks approved these changes

2022-11-09 07:25 UTC, pradiptapks commented
@sanjaychari I don't have a environment to test pr. The chages looks good to me. But I prefer a 2nd thought and test from @masco & @asyedham.

2022-11-09 08:10 UTC, asyedham requested changes

2022-11-09 08:10 UTC, asyedham commented on templates/ceph-storage.j2.j2
> +{% if manila_enabled %}
Please submit a separate PR for manila related changes as jetpack is not yet supporting it for OSP17

2022-11-14 12:38 UTC, asyedham approved these changes
LGTM!

2022-11-14 12:39 UTC, merged