generates the ssh-key
redhat-performance/jetpack pull request #91
Opened 2019-10-30 13:29 UTC by asyedham

Fixes the issue #90

2019-11-04 12:21 UTC, asyedham commented
@sai could you please have look

2019-11-05 14:18 UTC, smalleni requested changes

2019-11-05 14:18 UTC, smalleni commented on tasks/copykeys.yml
> +    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f {{ ansible_ssh_key }}
Check if {{ ansible_ssh_key }} exists and only generate if needed.

2019-11-13 12:29 UTC, venkataanil commented on tasks/copykeys.yml
> +    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f {{ ansible_ssh_key }}
Agree

2019-11-14 17:17 UTC, closed without merging